apiVersion: v1
kind: Secret
metadata:
  name: node1-user-data
  namespace: baremetal-operator-system
type: Opaque
stringData:
  userData: |
    #cloud-config
    users:
      - name: ubuntu
        ssh_authorized_keys:
          - <your public key>
        sudo: ALL=(ALL) NOPASSWD:ALL
        groups: sudo
        shell: /bin/bash
